# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test inference project
        run: go test -v ./inference

      - name: Test training project
        run: go test -v ./training
  build:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Check repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.8'

      - name: Build inference project
        run: go build -v ./inference/src/cmd/server/.

      - name: Build training project
        run: go build -v ./training/src/cmd/server/.
